### ISSUE TITLE
NEO HEALTH N WELLNESS BUT AGAINNN | Convert all configuration calls to Sparks/Neos to verify settings being set correctly

### ISSUE THREAD

**Issue by GalexY727** [Patribots4738/Crescendo2024#168]
## Bug + Feature
I don't particularly appreciate that we have the chance to redeploy the code and not be able to drive around, or even worse, be able to drive except when we auto-align we are going to break into someone's house... These are things that can be fixed with a "bit" of trickery...

## TODO:
- [x] Convert all parameter set calls to the robot to check and see if the set worked. If it didn't, try again after waiting a short while and print the error to the console.
- [x] Fix the measurement period to make velocity estimations more accurate
- [x] Make a getRelativePosition method and a getAbsolutePosition method which uses a boolean to see if we are using an absolute encoder on our Neo
- [x] Read [this](https://www.chiefdelphi.com/t/neo-not-working-during-practice-match/407018?u=galexy) and [that](https://www.chiefdelphi.com/t/psa-check-parameters-and-retry-burnflash-with-thread-sleeps-on-spark-maxes-to-make-sure-parameters-are-being-set-as-intended/446650?u=galexy) to be knowledgeable on why these changes are required in the first place.
