### ISSUE TITLE
FROM FIRST™️ AT 2024LAKE TO FIRST™️ ON EINSTEIN !!!!!! (tracking issue)

### ISSUE THREAD

**Issue by Jacob1010-h** [Patribots4738/Crescendo2024#290]
### Discussed in https://github.com/Patribots4738/Crescendo2024/discussions/287

<div type='discussions-op-text'>

<sup>Originally posted by **RudyG252** April 10, 2024</sup>
As always, feel free to edit this message and add more if you have other ideas
### Bot code:
- [ ] Evaluate the best way to get rin out of this country
- [x] double amp fix
- [ ] Evaluate the best way to get passing as fast as possible
- [ ] auto shootup speeds faster gooder
- [ ] make preload faster??
- [x] #291

### Scouting app:
- [x] Make selection scouting for auto
- [ ] Make selection scouting for teleop
- [ ] Include passing in data similar to jay's metric🍕 
- [x] Remove useless datapoints
  - this includes driving, human player, coop, amped speaker
- [x] Starting positions in auto (compatible with our 5.5p?)

### Frank's backend
- [ ] Redo ranking system
  - Pass
  - center vs wing auto weights (wing weighed much less)
  - different weights depending on where you pick up teleop
  - create metric for consistency/inconsistency score
- [ ] create match cutoff between day 1 and day 2 and allow viewing for all/day1/day2 data
  - make another slider to decide what qual to cut off at with days being labeled on that slider
- [ ] create option to not show dead matches 
- [ ] sort search table by match number 100% of the time (i believe it's just by the time the data is entered rn)
- [ ] create an actual process and template for alliance selection and strat meeting before event (not related to backed but important)
- [ ] alliance selection tab for show</div>

**Comment by GalexY727** [comment]
what is this issue i'm confused

**Comment by Jacob1010-h** [comment]
this allows us to  make issue from bullet points, and allows it to update the discussion. (less work for me to go back and click a single button) (let github do it)

**Comment by Jacob1010-h** [comment]
im just gonna close this, the discussion is already being updated
